apiVersion: v1
kind: Service
metadata:
  name: velero-backup-svc
  namespace: demo-app
spec:
  selector:
    app: velero-backup
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
